# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
- group: DemoVariables
- name: dockerfilePath
  value: '**/Dockerfile'
  
  # Agent VM image name
- name: vmImageName
  value: 'ubuntu-latest'
  

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(dockerImageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerConnectionName)
        tags: |
          $(build.buildId)
          latest
    - script: |
        az login --service-principal -u $(clientID) -p $(spSecret) --tenant $(tenantID)
        az acr login -n denoocecreg
        helm package ./charts/newchart --version $(Build.BuildNumber) \
          --destination $(Build.ArtifactStagingDirectory)
        az acr helm push \
          --name $(dockerImageRepository) \
          $(Build.ArtifactStagingDirectory)/$(dockerImageRepository)-$(Build.BuildNumber).tgz

# - stage: Deploy
#   displayName: Deploy stage
#   # dependsOn: Build

#   jobs:
#   - deployment: Deploy
#     displayName: Deploy
#     environment: pipelines-javascript-docker
#     pool:
#       vmImage: $(vmImageName)
#     strategy:
#       runOnce:
#         deploy:
#           steps:
#             - script: dir
#               workingDirectory: $(Build.SourcesDirectory)
            # - task: HelmInstaller@1
            #   displayName: Install helm version 3.1.1
            #   inputs:
            #     helmVersionToInstall: '3.1.1'
            # - task: HelmDeploy@0
            #   displayName: 'Helm Deploy'
            #   inputs:
            #     connectionType: 'Kubernetes Service Connection'
            #     kubernetesServiceConnection: 'KUBE'
            #     command: 'upgrade'
            #     chartType: 'Name'
            #     chartName: '$(containerRegistry)/newchart'
            #     releaseName: 'denoocecreg'

            # - script: |
            #     az login --service-principal -u $(clientID) -p $(spSecret) --tenant $(tenantID)
            #     az acr login -n denoocecreg

            # - task: HelmDeploy@0
            #   displayName: 'Package Helm Chart'
            #   inputs:
            #     command: 'package'
            #     chartPath: '$(Build.SourcesDirectory)/charts/newchart'
            #     chartVersion: '$(Build.BuildNumber)'
            #     save: false


#           - script: |
#               helm repo add denoocecreg denoocecreg.azurecr.io
#               helm repo update
#               exit 0
#           - task: HelmDeploy@0
#             inputs:
#               connectionType: 'Kubernetes Service Connection'
#               kubernetesServiceConnection: 'KUBE'
#               command: 'install'
#               chartType: 'Name'
#               chartName: 'denoocecreg/newchart'
#           # - task: HelmDeploy@0
#           #   inputs:
#           #     connectionType: 'Kubernetes Service Connection'
#           #     kubernetesServiceConnection: 'KUBE'
#           #     command: 'ls'